from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():
    return "Mangosteen AI Server Running"

@app.route("/callback", methods=["POST"])
def callback():
    return "LINE Webhook Connected"

if __name__ == "__main__":
    app.run()
